### ISSUE TITLE
`yarn install` is broken

### ISSUE THREAD

**Issue by nandorojo** [Expensify/react-native-live-markdown#586] opened 2024-12-13 21:37 UTC
```sh
# This file contains the result of Yarn building a package (@expensify/react-native-live-markdown@virtual:7ef6def9554689f801c96d7c46bf0917fbe998740596748f8c9c6e6a3e5a32930c4a319f6524d083f53d2f3c57885ecf9764b1d10daa29c14d4b12000e2eb237#npm:0.1.208)
# Script name: postinstall

command not found: patch-package
```

Looks like `yarn` of the consumer calls `postinstall` on dependencies, causing apps without patch-package installed to break when they install this lib.

To reproduce, run `yarn add ` this library

**Comment by tomekzaw** [comment] 2024-12-14 09:26
Duplicate of https://github.com/Expensify/react-native-live-markdown/issues/573

**Closed by tomekzaw** 2024-12-14 09:26 UTC
