### ISSUE TITLE
App crashes if parser uses a regex that is used in another worklet 

### ISSUE THREAD

**Issue by s77rt** [Expensify/react-native-live-markdown#574] opened 2024-12-08 18:32 UTC
Using same regex (or objects that contain regex) in multiple worklets causes a crash. This is possibly a bug in react-native-reanimated but I'm not sure. cc @tomekzaw You may have an idea on this

**Reproducible example**:

```tsx
function Markdown() {
  const regex = /\d/;

  useAnimatedStyle(() => {
    console.log(regex);
    return {};
  }, []);

  return (
    <MarkdownTextInput
      parser={() => {
        'worklet';
        console.log(regex);
        return [];
      }}
    />
  );
}
```

**Comment by tomekzaw** [comment] 2024-12-08 20:16
@s77rt Thanks for reporting this issue. I can see why using the same regex object in `useAnimatedStyle` and inside `parser` worklet could lead to crashes but I'll need to confirm why.

However, I'm not sure if this is the same bug as reported in https://github.com/Expensify/App/issues/52475. Note that PR enabling worklets in `react-native-live-markdown` (https://github.com/Expensify/react-native-live-markdown/pull/439) was released in 0.1.188 but Expensify App still uses 0.1.187.

**Comment by s77rt** [comment] 2024-12-08 20:23
The bug in https://github.com/Expensify/App/issues/52475 is different. I faced the crash while trying to update `react-native-live-markdown` (which includes the fix for that issue).

**Comment by tomekzaw** [comment] 2024-12-08 20:26
So the fix is in `expensify-common` and you wanted to bump `react-native-live-markdown` to get newer version of `expensify-common`, is that correct? What version of `expensify-common` is needed?

**Comment by s77rt** [comment] 2024-12-08 20:28
Correct! The needed version is 2.0.108

**Comment by tomekzaw** [comment] 2024-12-08 20:31
Alright, so we bumped `expensify-common` to 2.0.108 in `react-native-live-markdown` 0.1.192 which already uses worklets. Sounds like there's no easy way and we have to either use patch-package on top if 0.1.187 or just wait until this issue #574 is resolved. Let me know if anything else comes to your mind.

Maybe we should have released worklet support as 0.2.0 so we can keep 0.1.x versions with old engine. Sorry for inconvenience, we don't have much control over versioning scheme as the bot bumps the version in package.json and publishes to npm automatically.

**Comment by s77rt** [comment] 2024-12-08 20:43
I think I will just _avoid_ the problem. I doubt we need regex in worklets in E/App. It's being captured only because we reference a value that comes from an object [`CONST.ANIMATION_GYROSCOPE_VALUE`](https://github.com/Expensify/App/blob/b595f5d24141a403fcc3f44c73d00cd6951dca7d/src/pages/home/report/AnimatedEmptyStateBackground.tsx#L30-L45). But patching may be the best option and probably the safest.

**Comment by tomekzaw** [comment] 2024-12-08 20:46
Okay, in that case I'll leave the fix in E/App up to you. I will investigate the issue as it's probably rooted in reanimated/worklets.

**Comment by tomekzaw** [comment] 2024-12-08 20:57
I found the root cause of the issue. In Reanimated/Worklets, `RegExp` objects are cloned to worklet runtimes using `ShareableHandle` mechanism (see [here](https://github.com/software-mansion/react-native-reanimated/blob/3f864e6ae89d0edbbeedda17809c4ef9ea927622/packages/react-native-reanimated/src/shareables.ts#L358-L370)) via `__init` factory function that creates an instance of `RegExp` object on the target runtime.

The C++ implementation of `ShareableHandle::toJSValue` (see [here](https://github.com/software-mansion/react-native-reanimated/blob/3f864e6ae89d0edbbeedda17809c4ef9ea927622/packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp#L274-L292)) is first invoked on the live-markdown worklet runtime and stores the instance from live-markdown runtime in `remoteValue_` field (as well as the current runtime in `remoteRuntime_` pointer). Then, when `ShareableHandle::toJSValue` is called on the reanimated runtime, it reads `remoteValue_` belonging to another runtime (live-markdown worklet runtime). This leads to a crash. Currently, there's no mechanism to detect such case but it can be easily detected with `&rt == remoteRuntime_`. I will submit a PR to reanimated with the fix.

**Comment by s77rt** [comment] 2024-12-08 21:16
Thank you!

**Comment by tomekzaw** [comment] 2024-12-08 21:24
@s77rt Here's the fix in reanimated: https://github.com/software-mansion/react-native-reanimated/pull/6796

**Comment by Kicu** [comment] 2024-12-09 06:59
FYI @s77rt I will be bumping (or trying to 😅) live-markdown to the worklet supporting version, and `expensify-common` to newest this week.

**Closed** 2024-12-09 09:34 UTC
Labels: bug
